# Generated by Django 4.2 on 2023-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgamer',
            name='gamer_1',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='tournamentgamer',
            name='gamer_1_elo',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tournamentgamer',
            name='gamer_2',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='tournamentgamer',
            name='gamer_2_elo',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tournamentgamer',
            name='gamer_3',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='tournamentgamer',
            name='gamer_3_elo',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tournamentgamer',
            name='gamer_4',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='tournamentgamer',
            name='gamer_4_elo',
            field=models.IntegerField(default=1000),
        ),
    ]
