# Generated by Django 4.2 on 2023-04-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_tournament_is_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='is_teams',
            new_name='number_teams',
        ),
    ]
