# Generated by Django 4.2 on 2023-04-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_rename_is_teams_tournament_number_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='number_teams',
            field=models.IntegerField(default=0),
        ),
    ]
