# Generated by Django 4.2 on 2023-04-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_tournament_number_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentjourney',
            name='local_gamer',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='tournamentjourney',
            name='visitor_gamer',
            field=models.CharField(default='', max_length=140),
        ),
    ]
